import 'data.dart';
import 'db_kiddy_frame_entity.dart';
class KiddyFrameInitData {
  final KiddyFrameDatabase _db;
  KiddyFrameInitData(this._db);
  Future<void> initializeDefaultData() async {
    await _initFrameCategories();
    await _initDefaultFrames();
    await _initDefaultSettings();
    await _initDefaultBackgrounds();
    await _initDefaultStickers();
  }
  Future<void> _initFrameCategories() async {
    final categories = await _db.getFrameCategories();
    if (categories.isNotEmpty) return;
    final defaultCategories = [
      const FrameCategoryEntity(
        categoryId: 'simple',
        name: 'Simple',
        orderIndex: 1,
        isDefault: 1,
      ),
      const FrameCategoryEntity(
        categoryId: 'color',
        name: 'Color',
        orderIndex: 2,
        isDefault: 0,
      ),
      const FrameCategoryEntity(
        categoryId: 'cartoon',
        name: 'Cartoon',
        orderIndex: 3,
        isDefault: 0,
      ),
      const FrameCategoryEntity(
        categoryId: 'creative',
        name: 'Creative',
        orderIndex: 4,
        isDefault: 0,
      ),
      const FrameCategoryEntity(
        categoryId: 'festival',
        name: 'Festival',
        orderIndex: 5,
        isDefault: 0,
      ),
    ];
    for (final category in defaultCategories) {
      await _db.insertFrameCategory(category);
    }
  }
  Future<void> _initDefaultFrames() async {
    final frames = await _db.getFrames();
    if (frames.isNotEmpty) return;
    final defaultFrames = [
      const FrameEntity(
        frameId: 'creative_marjanno_001',
        name: 'Vintage Ornate',
        category: 'creative',
        filePath: 'assets/frames/creative/marjanno-frame-5455558_1920_副本.png',
        thumbnailPath:
            'assets/frames/creative/marjanno-frame-5455558_1920_副本.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 120,
        innerPaddingRight: 120,
        innerPaddingBottom: 120,
        innerPaddingLeft: 120,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'creative_vintage_001',
        name: 'Vintage Classic',
        category: 'creative',
        filePath: 'assets/frames/creative/vintage-ornate-001.png',
        thumbnailPath: 'assets/frames/creative/vintage-ornate-001.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 110,
        innerPaddingRight: 110,
        innerPaddingBottom: 110,
        innerPaddingLeft: 110,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'creative_artistic_001',
        name: 'Artistic Border',
        category: 'creative',
        filePath: 'assets/frames/creative/artistic-border-001.png',
        thumbnailPath: 'assets/frames/creative/artistic-border-001.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 120,
        innerPaddingRight: 120,
        innerPaddingBottom: 120,
        innerPaddingLeft: 120,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'simple_quicksandala_001',
        name: 'Elegant Frame',
        category: 'simple',
        filePath: 'assets/frames/simple/quicksandala-frame-1973489_1920_副本.png',
        thumbnailPath:
            'assets/frames/simple/quicksandala-frame-1973489_1920_副本.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 100,
        innerPaddingRight: 100,
        innerPaddingBottom: 100,
        innerPaddingLeft: 100,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'simple_wood_natural_001',
        name: 'Wood Natural',
        category: 'simple',
        filePath: 'assets/frames/simple/wood-natural-001.png',
        thumbnailPath: 'assets/frames/simple/wood-natural-001.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 90,
        innerPaddingRight: 90,
        innerPaddingBottom: 90,
        innerPaddingLeft: 90,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'simple_wood_classic_001',
        name: 'Wood Classic',
        category: 'simple',
        filePath: 'assets/frames/simple/wood-classic-001.png',
        thumbnailPath: 'assets/frames/simple/wood-classic-001.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 100,
        innerPaddingRight: 100,
        innerPaddingBottom: 100,
        innerPaddingLeft: 100,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'simple_thin_elegant_001',
        name: 'Thin Elegant',
        category: 'simple',
        filePath: 'assets/frames/simple/thin-elegant-001.png',
        thumbnailPath: 'assets/frames/simple/thin-elegant-001.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 60,
        innerPaddingRight: 60,
        innerPaddingBottom: 60,
        innerPaddingLeft: 60,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'simple_classic_border_001',
        name: 'Classic Border',
        category: 'simple',
        filePath: 'assets/frames/simple/classic-border-001.png',
        thumbnailPath: 'assets/frames/simple/classic-border-001.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 80,
        innerPaddingRight: 80,
        innerPaddingBottom: 80,
        innerPaddingLeft: 80,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'simple_silentvoice_001',
        name: 'Clean Frame 1',
        category: 'simple',
        filePath:
            'assets/frames/simple/silentvoice-photo-frame-1698482_1920_副本.png',
        thumbnailPath:
            'assets/frames/simple/silentvoice-photo-frame-1698482_1920_副本.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 80,
        innerPaddingRight: 80,
        innerPaddingBottom: 80,
        innerPaddingLeft: 80,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'simple_silentvoice_002',
        name: 'Clean Frame 2',
        category: 'simple',
        filePath:
            'assets/frames/simple/silentvoice-photo-frame-1698488_1920_副本.png',
        thumbnailPath:
            'assets/frames/simple/silentvoice-photo-frame-1698488_1920_副本.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 80,
        innerPaddingRight: 80,
        innerPaddingBottom: 80,
        innerPaddingLeft: 80,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'simple_silentvoice_003',
        name: 'Clean Frame 3',
        category: 'simple',
        filePath:
            'assets/frames/simple/silentvoice-photo-frame-1698489_1920_副本.png',
        thumbnailPath:
            'assets/frames/simple/silentvoice-photo-frame-1698489_1920_副本.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 80,
        innerPaddingRight: 80,
        innerPaddingBottom: 80,
        innerPaddingLeft: 80,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'simple_silentvoice_004',
        name: 'Clean Frame 4',
        category: 'simple',
        filePath:
            'assets/frames/simple/silentvoice-photo-frame-1698491_1920_副本.png',
        thumbnailPath:
            'assets/frames/simple/silentvoice-photo-frame-1698491_1920_副本.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 80,
        innerPaddingRight: 80,
        innerPaddingBottom: 80,
        innerPaddingLeft: 80,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'simple_silentvoice_005',
        name: 'Clean Frame 5',
        category: 'simple',
        filePath:
            'assets/frames/simple/silentvoice-photo-frame-1698492_1920_副本.png',
        thumbnailPath:
            'assets/frames/simple/silentvoice-photo-frame-1698492_1920_副本.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 80,
        innerPaddingRight: 80,
        innerPaddingBottom: 80,
        innerPaddingLeft: 80,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'simple_silentvoice_006',
        name: 'Clean Frame 6',
        category: 'simple',
        filePath:
            'assets/frames/simple/silentvoice-photo-frame-1698494_1920_副本.png',
        thumbnailPath:
            'assets/frames/simple/silentvoice-photo-frame-1698494_1920_副本.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 80,
        innerPaddingRight: 80,
        innerPaddingBottom: 80,
        innerPaddingLeft: 80,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'simple_silentvoice_007',
        name: 'Clean Frame 7',
        category: 'simple',
        filePath:
            'assets/frames/simple/silentvoice-photo-frame-1749824_1920_副本.png',
        thumbnailPath:
            'assets/frames/simple/silentvoice-photo-frame-1749824_1920_副本.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 80,
        innerPaddingRight: 80,
        innerPaddingBottom: 80,
        innerPaddingLeft: 80,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'color_red_border',
        name: 'Red',
        category: 'color',
        filePath: '',
        thumbnailPath: '',
        isPro: 0,
        supportColorChange: 0,
        defaultColors: '#FF0000',
        innerPaddingTop: 20,
        innerPaddingRight: 20,
        innerPaddingBottom: 20,
        innerPaddingLeft: 20,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'color_blue_border',
        name: 'Blue',
        category: 'color',
        filePath: '',
        thumbnailPath: '',
        isPro: 0,
        supportColorChange: 0,
        defaultColors: '#2196F3',
        innerPaddingTop: 20,
        innerPaddingRight: 20,
        innerPaddingBottom: 20,
        innerPaddingLeft: 20,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'color_green_border',
        name: 'Green',
        category: 'color',
        filePath: '',
        thumbnailPath: '',
        isPro: 0,
        supportColorChange: 0,
        defaultColors: '#4CAF50',
        innerPaddingTop: 20,
        innerPaddingRight: 20,
        innerPaddingBottom: 20,
        innerPaddingLeft: 20,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'color_yellow_border',
        name: 'Yellow',
        category: 'color',
        filePath: '',
        thumbnailPath: '',
        isPro: 0,
        supportColorChange: 0,
        defaultColors: '#FFC107',
        innerPaddingTop: 20,
        innerPaddingRight: 20,
        innerPaddingBottom: 20,
        innerPaddingLeft: 20,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'color_pink_border',
        name: 'Pink',
        category: 'color',
        filePath: '',
        thumbnailPath: '',
        isPro: 0,
        supportColorChange: 0,
        defaultColors: '#E91E63',
        innerPaddingTop: 20,
        innerPaddingRight: 20,
        innerPaddingBottom: 20,
        innerPaddingLeft: 20,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'color_purple_border',
        name: 'Purple',
        category: 'color',
        filePath: '',
        thumbnailPath: '',
        isPro: 0,
        supportColorChange: 0,
        defaultColors: '#9C27B0',
        innerPaddingTop: 20,
        innerPaddingRight: 20,
        innerPaddingBottom: 20,
        innerPaddingLeft: 20,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'color_orange_border',
        name: 'Orange',
        category: 'color',
        filePath: '',
        thumbnailPath: '',
        isPro: 0,
        supportColorChange: 0,
        defaultColors: '#FF5722',
        innerPaddingTop: 20,
        innerPaddingRight: 20,
        innerPaddingBottom: 20,
        innerPaddingLeft: 20,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'color_teal_border',
        name: 'Teal',
        category: 'color',
        filePath: '',
        thumbnailPath: '',
        isPro: 0,
        supportColorChange: 0,
        defaultColors: '#009688',
        innerPaddingTop: 20,
        innerPaddingRight: 20,
        innerPaddingBottom: 20,
        innerPaddingLeft: 20,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'cartoon_vector_fun_001',
        name: 'Vector Fun',
        category: 'cartoon',
        filePath: 'assets/frames/cartoon/vector-fun-001.png',
        thumbnailPath: 'assets/frames/cartoon/vector-fun-001.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 95,
        innerPaddingRight: 95,
        innerPaddingBottom: 95,
        innerPaddingLeft: 95,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'cartoon_decorative_colorful_001',
        name: 'Decorative Colorful',
        category: 'cartoon',
        filePath: 'assets/frames/cartoon/decorative-colorful-001.png',
        thumbnailPath: 'assets/frames/cartoon/decorative-colorful-001.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 105,
        innerPaddingRight: 105,
        innerPaddingBottom: 105,
        innerPaddingLeft: 105,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'cartoon_pattern_multicolor_001',
        name: 'Pattern Multicolor',
        category: 'cartoon',
        filePath: 'assets/frames/cartoon/pattern-multicolor-001.png',
        thumbnailPath: 'assets/frames/cartoon/pattern-multicolor-001.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 100,
        innerPaddingRight: 100,
        innerPaddingBottom: 100,
        innerPaddingLeft: 100,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'cartoon_pattern_multicolor_002',
        name: 'Pattern Multicolor 2',
        category: 'cartoon',
        filePath: 'assets/frames/cartoon/pattern-multicolor-002.png',
        thumbnailPath: 'assets/frames/cartoon/pattern-multicolor-002.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 100,
        innerPaddingRight: 100,
        innerPaddingBottom: 100,
        innerPaddingLeft: 100,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'cartoon_geometric_bright_001',
        name: 'Geometric Bright',
        category: 'cartoon',
        filePath: 'assets/frames/cartoon/geometric-bright-001.png',
        thumbnailPath: 'assets/frames/cartoon/geometric-bright-001.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 90,
        innerPaddingRight: 90,
        innerPaddingBottom: 90,
        innerPaddingLeft: 90,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'cartoon_geometric_bright_002',
        name: 'Geometric Bright 2',
        category: 'cartoon',
        filePath: 'assets/frames/cartoon/geometric-bright-002.png',
        thumbnailPath: 'assets/frames/cartoon/geometric-bright-002.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 90,
        innerPaddingRight: 90,
        innerPaddingBottom: 90,
        innerPaddingLeft: 90,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'cartoon_floral_colorful_001',
        name: 'Floral Colorful',
        category: 'cartoon',
        filePath: 'assets/frames/cartoon/floral-colorful-001.png',
        thumbnailPath: 'assets/frames/cartoon/floral-colorful-001.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 110,
        innerPaddingRight: 110,
        innerPaddingBottom: 110,
        innerPaddingLeft: 110,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'cartoon_floral_colorful_002',
        name: 'Floral Colorful 2',
        category: 'cartoon',
        filePath: 'assets/frames/cartoon/floral-colorful-002.png',
        thumbnailPath: 'assets/frames/cartoon/floral-colorful-002.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 110,
        innerPaddingRight: 110,
        innerPaddingBottom: 110,
        innerPaddingLeft: 110,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'festival_christmas_tree_001',
        name: 'Christmas Tree',
        category: 'festival',
        filePath: 'assets/frames/festival/christmas-tree-001.png',
        thumbnailPath: 'assets/frames/festival/christmas-tree-001.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 120,
        innerPaddingRight: 120,
        innerPaddingBottom: 120,
        innerPaddingLeft: 120,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'festival_santa_claus_001',
        name: 'Santa Claus',
        category: 'festival',
        filePath: 'assets/frames/festival/santa-claus-001.png',
        thumbnailPath: 'assets/frames/festival/santa-claus-001.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 130,
        innerPaddingRight: 130,
        innerPaddingBottom: 130,
        innerPaddingLeft: 130,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
      const FrameEntity(
        frameId: 'festival_heart_valentine_001',
        name: 'Heart Valentine',
        category: 'festival',
        filePath: 'assets/frames/festival/heart-valentine-001.png',
        thumbnailPath: 'assets/frames/festival/heart-valentine-001.png',
        isPro: 0,
        supportColorChange: 0,
        innerPaddingTop: 110,
        innerPaddingRight: 110,
        innerPaddingBottom: 110,
        innerPaddingLeft: 110,
        hasShadow: 0,
        adjustableOpacity: 0,
      ),
    ];
    for (final frame in defaultFrames) {
      await _db.insertFrame(frame);
    }
  }
  Future<void> _initDefaultSettings() async {
    final settings = await _db.getSettings();
    if (settings.isNotEmpty) return;
    final now = DateTime.now().toIso8601String();
    final defaultSettings = [
      SettingEntity(
        settingKey: 'default_format',
        settingValue: 'JPG',
        updatedAt: now,
      ),
      SettingEntity(
        settingKey: 'quality',
        settingValue: 'high',
        updatedAt: now,
      ),
      SettingEntity(
        settingKey: 'auto_save_to_album',
        settingValue: 'true',
        updatedAt: now,
      ),
      SettingEntity(
        settingKey: 'keep_exif',
        settingValue: 'false',
        updatedAt: now,
      ),
      SettingEntity(
        settingKey: 'naming_rule',
        settingValue: 'date_sequence',
        updatedAt: now,
      ),
      SettingEntity(
        settingKey: 'default_frame_category',
        settingValue: 'simple',
        updatedAt: now,
      ),
      SettingEntity(
        settingKey: 'show_tips',
        settingValue: 'true',
        updatedAt: now,
      ),
      SettingEntity(
        settingKey: 'preview_quality',
        settingValue: 'medium',
        updatedAt: now,
      ),
    ];
    for (final setting in defaultSettings) {
      await _db.insertSetting(setting);
    }
  }
  Future<void> _initDefaultBackgrounds() async {
    final backgrounds = await _db.getBackgrounds();
    if (backgrounds.isNotEmpty) return;
    final defaultBackgrounds = [
      const BackgroundEntity(
        backgroundId: 'color_white',
        name: 'White',
        type: 'color',
        colorValue: '#FFFFFF',
        isPro: 0,
      ),
      const BackgroundEntity(
        backgroundId: 'color_cream',
        name: 'Cream',
        type: 'color',
        colorValue: '#FFF8DC',
        isPro: 0,
      ),
      const BackgroundEntity(
        backgroundId: 'color_light_gray',
        name: 'Light Gray',
        type: 'color',
        colorValue: '#F5F5F5',
        isPro: 0,
      ),
      const BackgroundEntity(
        backgroundId: 'color_soft_pink',
        name: 'Soft Pink',
        type: 'color',
        colorValue: '#FFE4E1',
        isPro: 0,
      ),
      const BackgroundEntity(
        backgroundId: 'color_light_blue',
        name: 'Light Blue',
        type: 'color',
        colorValue: '#E6F3FF',
        isPro: 0,
      ),
      const BackgroundEntity(
        backgroundId: 'color_mint',
        name: 'Mint',
        type: 'color',
        colorValue: '#E0FFE0',
        isPro: 0,
      ),
      const BackgroundEntity(
        backgroundId: 'color_lavender',
        name: 'Lavender',
        type: 'color',
        colorValue: '#E6E6FA',
        isPro: 0,
      ),
      const BackgroundEntity(
        backgroundId: 'color_peach',
        name: 'Peach',
        type: 'color',
        colorValue: '#FFDAB9',
        isPro: 0,
      ),
      const BackgroundEntity(
        backgroundId: 'color_sky_blue',
        name: 'Sky Blue',
        type: 'color',
        colorValue: '#87CEEB',
        isPro: 1,
      ),
      const BackgroundEntity(
        backgroundId: 'color_coral',
        name: 'Coral',
        type: 'color',
        colorValue: '#FF7F50',
        isPro: 1,
      ),
      const BackgroundEntity(
        backgroundId: 'gradient_sunset',
        name: 'Sunset',
        type: 'gradient',
        colorValue:
            '{"colors":["#FF6B6B","#FFE66D"],"begin":"topLeft","end":"bottomRight"}',
        isPro: 0,
      ),
      const BackgroundEntity(
        backgroundId: 'gradient_ocean',
        name: 'Ocean',
        type: 'gradient',
        colorValue:
            '{"colors":["#4ECDC4","#556270"],"begin":"topCenter","end":"bottomCenter"}',
        isPro: 0,
      ),
      const BackgroundEntity(
        backgroundId: 'gradient_purple_dream',
        name: 'Purple Dream',
        type: 'gradient',
        colorValue:
            '{"colors":["#A8EDEA","#FED6E3"],"begin":"topLeft","end":"bottomRight"}',
        isPro: 0,
      ),
      const BackgroundEntity(
        backgroundId: 'gradient_forest',
        name: 'Forest',
        type: 'gradient',
        colorValue:
            '{"colors":["#134E5E","#71B280"],"begin":"topCenter","end":"bottomCenter"}',
        isPro: 0,
      ),
      const BackgroundEntity(
        backgroundId: 'gradient_fire',
        name: 'Fire',
        type: 'gradient',
        colorValue:
            '{"colors":["#FF416C","#FF4B2B"],"begin":"bottomLeft","end":"topRight"}',
        isPro: 0,
      ),
      const BackgroundEntity(
        backgroundId: 'gradient_sky',
        name: 'Sky',
        type: 'gradient',
        colorValue:
            '{"colors":["#667EEA","#764BA2"],"begin":"topLeft","end":"bottomRight"}',
        isPro: 1,
      ),
      const BackgroundEntity(
        backgroundId: 'gradient_rose',
        name: 'Rose',
        type: 'gradient',
        colorValue:
            '{"colors":["#F857A6","#FF5858"],"begin":"centerLeft","end":"centerRight"}',
        isPro: 1,
      ),
      const BackgroundEntity(
        backgroundId: 'gradient_gold',
        name: 'Gold',
        type: 'gradient',
        colorValue:
            '{"colors":["#FFD89B","#19547B"],"begin":"topRight","end":"bottomLeft"}',
        isPro: 1,
      ),
      const BackgroundEntity(
        backgroundId: 'image_cartoon_corn',
        name: 'Cartoon Corn',
        type: 'image',
        filePath: 'assets/bg/bg-cartoon-corn-001.png',
        thumbnailPath: 'assets/bg/bg-cartoon-corn-001.png',
        isPro: 0,
      ),
      const BackgroundEntity(
        backgroundId: 'image_cartoon_taxi',
        name: 'Cartoon Taxi',
        type: 'image',
        filePath: 'assets/bg/bg-cartoon-taxi-001.png',
        thumbnailPath: 'assets/bg/bg-cartoon-taxi-001.png',
        isPro: 0,
      ),
      const BackgroundEntity(
        backgroundId: 'image_heart_love',
        name: 'Heart Love',
        type: 'image',
        filePath: 'assets/bg/bg-heart-love-001.png',
        thumbnailPath: 'assets/bg/bg-heart-love-001.png',
        isPro: 0,
      ),
      const BackgroundEntity(
        backgroundId: 'image_leaves_nature',
        name: 'Nature Leaves',
        type: 'image',
        filePath: 'assets/bg/bg-leaves-nature-001.png',
        thumbnailPath: 'assets/bg/bg-leaves-nature-001.png',
        isPro: 1,
      ),
      const BackgroundEntity(
        backgroundId: 'image_flowers_pink',
        name: 'Pink Flowers',
        type: 'image',
        filePath: 'assets/bg/bg-flowers-pink-001.png',
        thumbnailPath: 'assets/bg/bg-flowers-pink-001.png',
        isPro: 1,
      ),
      const BackgroundEntity(
        backgroundId: 'image_flowers_purple',
        name: 'Purple Flowers',
        type: 'image',
        filePath: 'assets/bg/bg-flowers-purple-001.png',
        thumbnailPath: 'assets/bg/bg-flowers-purple-001.png',
        isPro: 1,
      ),
    ];
    for (final background in defaultBackgrounds) {
      await _db.insertBackground(background);
    }
  }
  Future<void> _initDefaultStickers() async {
    final stickers = await _db.getStickers();
    if (stickers.isNotEmpty) return;
    final defaultStickers = [
      const StickerEntity(
        stickerId: 'rating_five_stars',
        name: 'Five Stars',
        category: 'rating',
        filePath: 'assets/stickers/rating/five-stars.png',
        thumbnailPath: 'assets/stickers/rating/five-stars.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'rating_three_stars',
        name: 'Three Stars',
        category: 'rating',
        filePath: 'assets/stickers/rating/three-stars.png',
        thumbnailPath: 'assets/stickers/rating/three-stars.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'rating_gold_medal',
        name: 'Gold Medal',
        category: 'rating',
        filePath: 'assets/stickers/rating/gold-medal.png',
        thumbnailPath: 'assets/stickers/rating/gold-medal.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'rating_silver_medal',
        name: 'Silver Medal',
        category: 'rating',
        filePath: 'assets/stickers/rating/silver-medal.png',
        thumbnailPath: 'assets/stickers/rating/silver-medal.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'rating_bronze_medal',
        name: 'Bronze Medal',
        category: 'rating',
        filePath: 'assets/stickers/rating/bronze-medal.png',
        thumbnailPath: 'assets/stickers/rating/bronze-medal.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'rating_100_points',
        name: '100 Points',
        category: 'rating',
        filePath: 'assets/stickers/rating/100-points.png',
        thumbnailPath: 'assets/stickers/rating/100-points.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'rating_a_plus',
        name: 'A Plus',
        category: 'rating',
        filePath: 'assets/stickers/rating/a-plus.png',
        thumbnailPath: 'assets/stickers/rating/a-plus.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'rating_thumbs_up',
        name: 'Thumbs Up',
        category: 'rating',
        filePath: 'assets/stickers/rating/thumbs-up.png',
        thumbnailPath: 'assets/stickers/rating/thumbs-up.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'festival_christmas_tree',
        name: 'Christmas Tree',
        category: 'festival',
        filePath: 'assets/stickers/festival/christmas-tree.png',
        thumbnailPath: 'assets/stickers/festival/christmas-tree.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'festival_santa_claus',
        name: 'Santa Claus',
        category: 'festival',
        filePath: 'assets/stickers/festival/santa-claus.png',
        thumbnailPath: 'assets/stickers/festival/santa-claus.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'festival_snowman',
        name: 'Snowman',
        category: 'festival',
        filePath: 'assets/stickers/festival/snowman.png',
        thumbnailPath: 'assets/stickers/festival/snowman.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'festival_birthday_cake',
        name: 'Birthday Cake',
        category: 'festival',
        filePath: 'assets/stickers/festival/birthday-cake.png',
        thumbnailPath: 'assets/stickers/festival/birthday-cake.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'festival_balloons',
        name: 'Balloons',
        category: 'festival',
        filePath: 'assets/stickers/festival/balloons.png',
        thumbnailPath: 'assets/stickers/festival/balloons.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'festival_party_hat',
        name: 'Party Hat',
        category: 'festival',
        filePath: 'assets/stickers/festival/party-hat.png',
        thumbnailPath: 'assets/stickers/festival/party-hat.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'festival_valentine_heart',
        name: 'Valentine Heart',
        category: 'festival',
        filePath: 'assets/stickers/festival/valentine-heart.png',
        thumbnailPath: 'assets/stickers/festival/valentine-heart.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'festival_halloween_pumpkin',
        name: 'Halloween Pumpkin',
        category: 'festival',
        filePath: 'assets/stickers/festival/halloween-pumpkin.png',
        thumbnailPath: 'assets/stickers/festival/halloween-pumpkin.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'festival_easter_egg',
        name: 'Easter Egg',
        category: 'festival',
        filePath: 'assets/stickers/festival/easter-egg.png',
        thumbnailPath: 'assets/stickers/festival/easter-egg.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'praise_excellent',
        name: 'Excellent',
        category: 'praise',
        filePath: 'assets/stickers/praise/excellent.png',
        thumbnailPath: 'assets/stickers/praise/excellent.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'praise_great_job',
        name: 'Great Job',
        category: 'praise',
        filePath: 'assets/stickers/praise/great-job.png',
        thumbnailPath: 'assets/stickers/praise/great-job.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'praise_well_done',
        name: 'Well Done',
        category: 'praise',
        filePath: 'assets/stickers/praise/well-done.gif',
        thumbnailPath: 'assets/stickers/praise/well-done.gif',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'praise_amazing',
        name: 'Amazing',
        category: 'praise',
        filePath: 'assets/stickers/praise/amazing.png',
        thumbnailPath: 'assets/stickers/praise/amazing.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'deco_flower_border',
        name: 'Flower Border',
        category: 'decoration',
        filePath: 'assets/stickers/decoration/flower-border.png',
        thumbnailPath: 'assets/stickers/decoration/flower-border.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'deco_crown',
        name: 'Crown',
        category: 'decoration',
        filePath: 'assets/stickers/decoration/crown.png',
        thumbnailPath: 'assets/stickers/decoration/crown.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'deco_star_sparkle',
        name: 'Star Sparkle',
        category: 'decoration',
        filePath: 'assets/stickers/decoration/star-sparkle.png',
        thumbnailPath: 'assets/stickers/decoration/star-sparkle.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'deco_rainbow',
        name: 'Rainbow',
        category: 'decoration',
        filePath: 'assets/stickers/decoration/rainbow.png',
        thumbnailPath: 'assets/stickers/decoration/rainbow.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'deco_ribbon',
        name: 'Ribbon',
        category: 'decoration',
        filePath: 'assets/stickers/decoration/ribbon.png',
        thumbnailPath: 'assets/stickers/decoration/ribbon.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'deco_cloud',
        name: 'Cloud',
        category: 'decoration',
        filePath: 'assets/stickers/decoration/cloud.png',
        thumbnailPath: 'assets/stickers/decoration/cloud.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'deco_sun',
        name: 'Sun',
        category: 'decoration',
        filePath: 'assets/stickers/decoration/sun.png',
        thumbnailPath: 'assets/stickers/decoration/sun.png',
        isPro: 0,
      ),
      const StickerEntity(
        stickerId: 'deco_moon',
        name: 'Moon',
        category: 'decoration',
        filePath: 'assets/stickers/decoration/moon.png',
        thumbnailPath: 'assets/stickers/decoration/moon.png',
        isPro: 0,
      ),
    ];
    for (final sticker in defaultStickers) {
      await _db.insertSticker(sticker);
    }
  }
}
